### ISSUE TITLE
Order/Assemble new Swerve drivetrain

### ISSUE THREAD

**Issue by mckartha** [FRC830/2023-Tasks#12]
Jeffrey and Ethan requested parts for a 2nd Swerve drive

**Comment by mckartha** [comment]
**Status** 2023Jan24
* Three swerve modules built 
* one left to build

**Additional Sub-Tasks**
* [ ] need to 3d-print spacers for 
* [ ] get more shaft keys to use with these motors 
  *  [x] there are more in the toolbox
* [ ] get another Neo

**Comment by WJiarong** [comment]
![Image](https://user-images.githubusercontent.com/123536143/214496245-0f9380d7-52e0-422e-b8ac-af9e58747dc7.jpg)



![Image](https://user-images.githubusercontent.com/123536143/214496409-f73c8ddc-e432-4ff6-b1b9-b97b890b03da.png)
