### ISSUE TITLE
Test the Intake prototype and improve; demonstrate

### ISSUE THREAD

**Issue by mckartha** [FRC830/2023-Tasks#24]

**Comment by Lordoffish** [comment]
Negatives
- Only works when flush against the ground. 
- Pneumatic arms don't add much to functionality.
Questions
- How to get it to ground level?
- how will the arm access the field items from the intake?
- Is building a separate intake from the outage provide any advantages and what are those advantages?

**Comment by KDJ445** [comment]
https://user-images.githubusercontent.com/123688192/215354013-2b8ca98d-c837-4b61-823e-5841e932497b.mp4

**Comment by KDJ445** [comment]
https://user-images.githubusercontent.com/123688192/215924203-ffcd38c9-87be-4e3e-a1a2-d9fc144e4fca.MOV

**Comment by Lordoffish** [comment]
https://user-images.githubusercontent.com/123338456/215924477-e251219c-3e61-488b-8814-4c6535fe6c8c.mp4

**Comment by KDJ445** [comment]
![Uploading BC4B98CE-91F1-4FF2-BB95-562E0C82D0A0.jpeg…]()
